### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by TheAdminKing** [flowroute/flowroute-numbers-ruby#3]
This file needs to be update for the initial install of the libraries on step number 5:

What you have:

gem build flowroute_messaging.gemspec
gem build flowroute_messaging-1.0.gem

should be:

gem build flowroute_numbers.gemspec
gem build flowroute_numbers-1.0.gem

**Comment by stmisc** [comment]
Fixed the file name issue and pushed the updated file.
